# Generated by Django 2.2.1 on 2019-05-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0007_remove_post_address1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file2',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
