# Generated by Django 2.2.1 on 2019-05-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0008_post_file2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contact',
            field=models.CharField(default='핸드폰번호', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='실명', max_length=15),
        ),
        migrations.AddField(
            model_name='post',
            name='sex',
            field=models.CharField(default='여성 or 남성', max_length=10),
        ),
    ]
