# Generated by Django 2.2.1 on 2019-05-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0010_auto_20190524_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
