# Generated by Django 2.2.1 on 2019-05-25 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0011_auto_20190524_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file2',
        ),
    ]
