# Generated by Django 2.2.1 on 2019-05-25 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0012_remove_post_file2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file1',
        ),
    ]
