# Generated by Django 2.2.1 on 2019-05-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0014_post_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
    ]
